mes=int(input("ingresa un numero de mes: "))
match mes:
     case 1: print("enero")
     case 2: print("febrero")
     case 3: print("marzo")
     case 4: print("abril")
     case 5: print("mayo")
     case 6: print("junio")
     case 7: print("julio")
     case 8: print("agosto")
     case 9: print("septiembre")
     case 10: print("octubre")
     case 11: print("noviembre")
     case 12: print("diciembre") 
