print("hola, escribe un numero entero")
numero1 = int(input())
print("ahora escribe otro numero entero")
numero2= int(input())
print("el primero numero mostrado es", numero1, " y el segundo numero mostrado es ", numero2)